### ISSUE TITLE
Imperial Rising Sun Symbology

### ISSUE THREAD

**Issue by brianherbert** [getchopstick/getchopstick.github.io#10]
I'm not personally offended but using components of the imperialist rising sun flag near the footer of your website is akin to including a swastika in many parts of the world. You may want to consider something else in it's place.

<img width="618" alt="screen shot 2017-07-05 at 2 52 19 pm" src="https://user-images.githubusercontent.com/106068/27880080-bace3cd6-6191-11e7-8bf8-f16670ec8280.png">

**Comment by Dietr** [comment]
Thanks for pointing this out. It was meant as a visual reference to the karate kid movies which was the inspiration of the Chopstick name (https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fgaleri.uludagsozluk.com%2F15%2Fkarate-kid_66852.jpg&f=1). But I understand your point so I removed it.

**Comment by brianherbert** [comment]
@dietr no problem. I didn't catch the karate kid reference :)
