### ISSUE TITLE
Confusion of design framework vs boilerplate

### ISSUE THREAD

**Issue by xavez** [getchopstick/getchopstick.github.io#7]
Hi Everyone

I’ve asked for some feedback on the website from some people and one thing that stood out is that there is no clear call to action anymore. Someone who is interested now has to make the distinction between using the “Design framework” and the “Boilerplate”.

I would argue most people coming to the website would want to download the Boilerplate and get started. More technical people will look a bit further and maybe find the design framework. But I think the main marketing message should be to lead people to the Boilerplate and get them started as soon as possible.

When someone is met with the choice on http://getchopstick.com/#start, they freeze because both blocks look very similar and Design framework vs Boilerplate is not a distinction everyone understands. If we want to keep this distinction, we would probably want to make it more clear what is for who. Although I would be a strong proponent of a hierarchical approach (Boilerplate first, design framework second)

Thoughts?

**Comment by Dietr** [comment]
Solution:
- [ ] Rewrite title/introduction > focus on static site prototyping/design in the browser
- [ ] 1 card with explanation about the boilerplate, scss framework as subsection
- [ ] Main github link goes to boilerplate
